{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ui.serviceAccountName" . }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.global.serviceAccount.automount }}
{{- end }}
